version: "3.8"

services:
  app:
    build: .
    environment:
      FLASK_APP: ${FLASK_APP}
      FLASK_ENV: ${FLASK_ENV}
      FLASK_DEBUG: ${FLASK_DEBUG}
      MONGO_URI: ${MONGO_URI}
      SECRET_KEY: ${SECRET_KEY}
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    links:
      - mongodb
    networks:
      - mongo-compose-network

  mongo-express:
    image: mongo-express
    restart: always
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
    ports:
      - "8081:8081"
    links:
      - mongodb
    networks:
      - mongo-compose-network

  mongodb:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_DATABASE: users
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - dbdata:/data/db
    networks:
      - mongo-compose-network

networks:
  mongo-compose-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
